### ISSUE TITLE
Refactor Entrypoint and Configuration

### ISSUE THREAD

**Issue by ivanleoncz** [ivanlmj/PyCaptive#15]
1. Application entrypoint.
2. Define pycaptive.ini
3. App configuration (pycaptive.ini file).
4. wsgi.py for gunicorn execution via systemd

**Comment by categulario** [comment]
lo único interesante ahí es que la línea
```
app.config.from_object('settings.ProductionConfig')
```
está un poco hardcodeada todavía, y con las variables de entorno no hay nada hardcodeado. ¿Qué onda, cuándo nos vemos otra vez?

**Comment by ivanlmj** [comment]
Next week @categulario . Soy un poco desconfiado con las variables de entorno (todavía) y siento que la configuración por objeto es más explicita y estrcturada en cuestión de código, pero estoy abierto a cambiar este concepto :+1: .
